/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Persistencia;

/**
 *
 * @author sortkrage
 */
public class ControlUsu extends javax.swing.JDialog {

    Persistencia p;
    Usuario usu;

    /**
     * Creates new form ControlUsu
     *
     * @param parent
     * @param modal
     */
    public ControlUsu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        p = Login._CONEXION;
        usu = Main._USU;

        initComponents();

        setLocationRelativeTo(this);
        jLabelError.setVisible(false);
        jLabelCambio.setVisible(false);
        jPanelContrasenia.setVisible(false);

        cargarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldApe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNick = new javax.swing.JTextField();
        jButtonContrasenia = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jPanelContrasenia = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelError = new javax.swing.JLabel();
        jLabelCambio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informacion sobre " + usu.getNick());

        jPanel1.setBackground(java.awt.Color.black);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crowIcon.png"))); // NOI18N
        jLabel3.setText("Sort Krage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
        );

        jLabel1.setText("Nombre: ");

        jTextFieldNom.setEditable(false);

        jLabel2.setText("Apellido: ");

        jTextFieldApe.setEditable(false);
        jTextFieldApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApeActionPerformed(evt);
            }
        });

        jLabel4.setText("Nick: ");

        jTextFieldNick.setEditable(false);

        jButtonContrasenia.setText("Cambiar Contraseña");
        jButtonContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContraseniaActionPerformed(evt);
            }
        });

        jButtonMod.setText("Modificar");
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jLabel5.setText("Nueva contraseña: ");

        javax.swing.GroupLayout jPanelContraseniaLayout = new javax.swing.GroupLayout(jPanelContrasenia);
        jPanelContrasenia.setLayout(jPanelContraseniaLayout);
        jPanelContraseniaLayout.setHorizontalGroup(
            jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContraseniaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanelContraseniaLayout.setVerticalGroup(
            jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContraseniaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelError.setForeground(java.awt.Color.red);
        jLabelError.setText("* No disponible");

        jLabelCambio.setText("* Contraseña cambiada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jTextFieldNick)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldApe, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelError))
                .addGap(31, 31, 31))
            .addComponent(jPanelContrasenia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCambio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContrasenia)
                    .addComponent(jButtonMod))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApeActionPerformed

    private void jButtonContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContraseniaActionPerformed
        // TODO add your handling code here:

        if (jButtonContrasenia.getText().equals("Cambiar")) {

            String pass = new String(jPasswordField1.getPassword());

            if (!pass.trim().isEmpty()) {

                try {

                    p.cambiarPass(usu, pass);
                    jLabelCambio.setVisible(true);
                    jPanelContrasenia.setVisible(false);

                } catch (SQLException ex) {
                    Logger.getLogger(ControlUsu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {

                JOptionPane.showMessageDialog(this, "No se puede poner una contraseña vacia",
                        "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } else {

            jPanelContrasenia.setVisible(true);
            jPanelContrasenia.grabFocus();
            jButtonContrasenia.setText("Cambiar");

        }
    }//GEN-LAST:event_jButtonContraseniaActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        // TODO add your handling code here:

        if (jButtonMod.getText().equals("Aceptar")) {

            Usuario nUsu = new Usuario();
            nUsu.setNick(jTextFieldNick.getText());
            nUsu.setNombre(jTextFieldNom.getText());
            nUsu.setApellido(jTextFieldApe.getText());

            try {

                if (!usu.getNick().equals(nUsu.getNick()) && p.comprobarNick(jTextFieldNick.getText())) {

                    jLabelError.setVisible(true);

                } else {

                    p.actualizarUsu(usu.getId(), nUsu);
                    jLabelError.setVisible(false);

                    jTextFieldNick.setEditable(false);
                    jTextFieldNick.grabFocus();
                    jTextFieldNom.setEditable(false);
                    jTextFieldApe.setEditable(false);
                    jLabelCambio.setText("* Información Actualizada");
                    jLabelCambio.setVisible(true);
                    jButtonMod.setText("Modificar");

                }

            } catch (SQLException ex) {
                Logger.getLogger(ControlUsu.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

            jTextFieldNick.setEditable(true);
            jTextFieldNick.grabFocus();
            jTextFieldNom.setEditable(true);
            jTextFieldApe.setEditable(true);
            jLabelCambio.setVisible(false);
            jButtonMod.setText("Aceptar");
        }


    }//GEN-LAST:event_jButtonModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ControlUsu dialog = new ControlUsu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContrasenia;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCambio;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContrasenia;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldApe;
    private javax.swing.JTextField jTextFieldNick;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables

    private void cargarInfo() {

        try {

            Usuario u = p.getUsuario(usu);

            jTextFieldNick.setText(usu.getNick());
            jTextFieldNom.setText(u.getNombre());
            jTextFieldApe.setText(u.getApellido());

        } catch (SQLException ex) {
            Logger.getLogger(ControlUsu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
